In [1]:
# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np

In [2]:
df=pd.read_csv("spacex_launch_dash.csv")
#df=pd.read_csv("dataset_part_1.csv") (Can uses this if using from Github)
df.head(10)

,Unnamed: 0,Flight Number,Launch Site,Mission Outcome,class,Payload Mass (kg),Booster Version,Booster Version Category
0,0,1,CCAFS LC-40,Success,0,0.0,F9 v1.0 B0003,v1.0
1,1,2,CCAFS LC-40,Success,0,0.0,F9 v1.0 B0004,v1.0
2,2,3,CCAFS LC-40,Success,0,525.0,F9 v1.0 B0005,v1.0
3,3,4,CCAFS LC-40,Success,0,500.0,F9 v1.0 B0006,v1.0
4,4,5,CCAFS LC-40,Success,0,677.0,F9 v1.0 B0007,v1.0
5,5,7,CCAFS LC-40,Success,0,3170.0,F9 v1.1,v1.1
6,6,8,CCAFS LC-40,Success,0,3325.0,F9 v1.1,v1.1
7,7,9,CCAFS LC-40,Success,0,2296.0,F9 v1.1,v1.1
8,8,10,CCAFS LC-40,Success,0,1316.0,F9 v1.1,v1.1
9,9,11,CCAFS LC-40,Success,0,4535.0,F9 v1.1,v1.1

In [4]:
number_of_launches_per_site = df['Launch Site'].value_counts()
number_of_launches_per_site

CCAFS LC-40     26
KSC LC-39A      13
VAFB SLC-4E     10
CCAFS SLC-40     7
Name: Launch Site, dtype: int64

In [14]:
rf = df.groupby(['Launch Site'], as_index=False)['class'].mean()
rf.rename(columns={'class':'SuccessRate'},inplace=True) #Change the name to represent.
rf

    Launch Site  SuccessRate
0   CCAFS LC-40     0.269231
1  CCAFS SLC-40     0.428571
2    KSC LC-39A     0.769231
3   VAFB SLC-4E     0.400000